//异步操作要保证一定的执行顺序就会导致回调地狱 一层一层嵌套看起来也不好看.
解决:
promise 对象 链式调用
无论是哪个 then 出了问题 都会跳到catch中

手动 控制then 结束可以手动创建 err 对象  抛出一个错误 程序会跳入catch 方法.
理解很重要 因为node中异步操作很重要 (这也是它很好的支持高并发的原因);

```javascript 

function test(){
return Promise((resolve , reject)=>{

    // 需要的异步处理

    // 成功 resolve 

    // 失败 reject
    })
}
```
2. 根据顺序 形成链式调用
    test().then().then().catch() 
3. 捕获错误


### node 
